import {
  BarChart3,
  BookOpenCheck,
  BriefcaseBusiness,
  Building2,
  CalendarClock,
  ClipboardCheck,
  ClipboardList,
  ClipboardPlus,
  Database,
  FileCheck2,
  FilePlus2,
  FileSearch,
  Files,
  GraduationCap,
  Handshake,
  Headphones,
  LayoutDashboard,
  Megaphone,
  RefreshCw,
  Scale,
  ShieldCheck,
  Target,
  TicketCheck,
  TriangleAlert,
  Users,
  WalletCards,
  Wrench,
} from "lucide-react";
import { ACCESS_ROLES } from "./roleAccess";

const item = (path, label, icon, minimumRole) => ({ path, label, icon, minimumRole });
const group = (label, icon, children) => ({ label, icon, children });

const workflowMenu = ({
  queueLabel,
  createLabel,
  portfolioLabel,
  policyLabel = "Related Policies",
  renewalLabel = "Renewals",
  reportsLabel,
  masterLabel,
  workIcon = ClipboardList,
  portfolioIcon = Files,
}) => [
  item("", "Dashboard", LayoutDashboard),
  group(queueLabel, workIcon, [
    item("reports", reportsLabel, ClipboardCheck),
    item("form", createLabel, ClipboardPlus),
  ]),
  group(portfolioLabel, portfolioIcon, [
    item("policies", policyLabel, Files),
    item("renewals", renewalLabel, RefreshCw),
  ]),
  item("master", masterLabel, Database, ACCESS_ROLES.MANAGER),
];

export const DEPARTMENT_MENUS = Object.freeze({
  administration: [
    item("", "Dashboard", LayoutDashboard),
    group("Reports", BarChart3, [
      item("pos-business-report", "POS Business Report", BriefcaseBusiness),
      item("pos-month-report", "POS Month Report", CalendarClock),
      item("employee-business-report", "Employee Business Report", Users),
      item("reports", "Administration Task Register", ClipboardCheck),
    ]),
    group("Administration", Building2, [
      item("form", "Create Admin Task", ClipboardPlus),
    ]),
    group("Department Data", Files, [
      item("policies", "Policy Access", Files),
      item("renewals", "Renewal Access", RefreshCw),
    ]),
    item("master", "Department Master", Database, ACCESS_ROLES.MANAGER),
  ],
  sales: workflowMenu({
    queueLabel: "Sales Pipeline",
    createLabel: "Create Lead",
    portfolioLabel: "Business Book",
    reportsLabel: "Lead Register",
    masterLabel: "Sales Master",
    workIcon: Target,
    portfolioIcon: BriefcaseBusiness,
  }),
  underwriting: workflowMenu({
    queueLabel: "Risk Desk",
    createLabel: "Create Risk Review",
    portfolioLabel: "Policy Review",
    reportsLabel: "Underwriting Register",
    masterLabel: "Risk Master",
    workIcon: ShieldCheck,
    portfolioIcon: FileSearch,
  }),
  claims: workflowMenu({
    queueLabel: "Claims Desk",
    createLabel: "Register Claim",
    portfolioLabel: "Claim Policies",
    reportsLabel: "Claims Register",
    masterLabel: "Claims Master",
    workIcon: FileCheck2,
  }),
  "customer-support": workflowMenu({
    queueLabel: "Service Desk",
    createLabel: "Create Service Request",
    portfolioLabel: "Customer Policies",
    reportsLabel: "Request Register",
    masterLabel: "Service Master",
    workIcon: Headphones,
    portfolioIcon: TicketCheck,
  }),
  renewal: [
    item("", "Dashboard", LayoutDashboard),
    item("renewals", "Upcoming Policy", RefreshCw),
    item("lapsed-policy", "Lapsed Policy", TriangleAlert),
    item("reports", "Follow-up Report", ClipboardCheck),
    group("Policy Entry", FilePlus2, [
      item("motor-entry", "Motor Entry", FilePlus2),
    ]),
  ],
  finance: workflowMenu({
    queueLabel: "Finance Desk",
    createLabel: "Create Transaction",
    portfolioLabel: "Policy Finance",
    reportsLabel: "Transaction Register",
    masterLabel: "Finance Master",
    workIcon: WalletCards,
  }),
  "information-technology": workflowMenu({
    queueLabel: "IT Service Desk",
    createLabel: "Create Ticket",
    portfolioLabel: "Business Systems",
    policyLabel: "Linked Policies",
    renewalLabel: "Scheduled Work",
    reportsLabel: "Ticket Register",
    masterLabel: "Asset Master",
    workIcon: Wrench,
    portfolioIcon: TicketCheck,
  }),
  marketing: workflowMenu({
    queueLabel: "Campaigns",
    createLabel: "Create Campaign",
    portfolioLabel: "Campaign Business",
    reportsLabel: "Campaign Register",
    masterLabel: "Marketing Master",
    workIcon: Megaphone,
    portfolioIcon: Target,
  }),
  compliance: workflowMenu({
    queueLabel: "Compliance Desk",
    createLabel: "Create Review",
    portfolioLabel: "Control Coverage",
    reportsLabel: "Review Register",
    masterLabel: "Compliance Master",
    workIcon: ShieldCheck,
    portfolioIcon: BookOpenCheck,
  }),
  legal: workflowMenu({
    queueLabel: "Legal Matters",
    createLabel: "Create Matter",
    portfolioLabel: "Case Coverage",
    reportsLabel: "Matter Register",
    masterLabel: "Legal Master",
    workIcon: Scale,
    portfolioIcon: Files,
  }),
  training: workflowMenu({
    queueLabel: "Training",
    createLabel: "Create Session",
    portfolioLabel: "Training Coverage",
    policyLabel: "Linked Policies",
    renewalLabel: "Upcoming Sessions",
    reportsLabel: "Session Register",
    masterLabel: "Training Master",
    workIcon: GraduationCap,
    portfolioIcon: Users,
  }),
  "business-development": workflowMenu({
    queueLabel: "Opportunities",
    createLabel: "Create Opportunity",
    portfolioLabel: "Business Pipeline",
    reportsLabel: "Opportunity Register",
    masterLabel: "BD Master",
    workIcon: Handshake,
    portfolioIcon: BriefcaseBusiness,
  }),
  audit: workflowMenu({
    queueLabel: "Audit Desk",
    createLabel: "Create Audit",
    portfolioLabel: "Audit Coverage",
    reportsLabel: "Audit Register",
    masterLabel: "Audit Master",
    workIcon: ClipboardCheck,
    portfolioIcon: FileSearch,
  }),
  "risk-management": workflowMenu({
    queueLabel: "Risk Register",
    createLabel: "Create Risk",
    portfolioLabel: "Risk Coverage",
    reportsLabel: "Risk Register",
    masterLabel: "Risk Master",
    workIcon: TriangleAlert,
    portfolioIcon: ShieldCheck,
  }),
  crm: workflowMenu({
    queueLabel: "Customer Desk",
    createLabel: "Create Interaction",
    portfolioLabel: "Customer Portfolio",
    reportsLabel: "Interaction Register",
    masterLabel: "CRM Master",
    workIcon: Users,
    portfolioIcon: BriefcaseBusiness,
  }),
});

export const getDepartmentMenu = (slug) => DEPARTMENT_MENUS[slug] || [
  item("", "Dashboard", LayoutDashboard),
  group("Work", ClipboardList, [
    item("reports", "Work Register", BarChart3),
    item("form", "Add Entry", ClipboardPlus),
  ]),
  group("Portfolio", Files, [
    item("policies", "Policies", Files),
    item("renewals", "Renewals", RefreshCw),
  ]),
  item("master", "Master", Database, ACCESS_ROLES.MANAGER),
];
