export const DEPARTMENT_DEFINITIONS = Object.freeze([
  { slug: "administration", label: "Administration" },
  { slug: "operations", label: "Operations", specialized: true },
  { slug: "accounts", label: "Accounts", specialized: true },
  { slug: "sales", label: "Sales" },
  { slug: "pos-management", label: "POS Management" },
  { slug: "underwriting", label: "Underwriting" },
  { slug: "claims", label: "Claims" },
  { slug: "customer-support", label: "Customer Support" },
  { slug: "renewal", label: "Renewal" },
  { slug: "finance", label: "Finance" },
  { slug: "human-resources", label: "Human Resources (HR)" },
  { slug: "information-technology", label: "Information Technology (IT)" },
  { slug: "marketing", label: "Marketing" },
]);
